cmake_minimum_required(VERSION 3.20)

if(NOT DEFINED SMROBOT_PACKAGE_EXAMPLES_SDK_PREFIX OR
   "${SMROBOT_PACKAGE_EXAMPLES_SDK_PREFIX}" STREQUAL "")
    message(FATAL_ERROR "SMROBOT_PACKAGE_EXAMPLES_SDK_PREFIX is required.")
endif()

if(NOT DEFINED SMROBOT_PACKAGE_EXAMPLES_CHECK_ROOT OR
   "${SMROBOT_PACKAGE_EXAMPLES_CHECK_ROOT}" STREQUAL "")
    set(SMROBOT_PACKAGE_EXAMPLES_CHECK_ROOT
        "${CMAKE_CURRENT_BINARY_DIR}/smrobot_package_component_checks")
endif()

if(NOT DEFINED SMROBOT_PACKAGE_EXAMPLES_GENERATOR OR
   "${SMROBOT_PACKAGE_EXAMPLES_GENERATOR}" STREQUAL "")
    set(_smrobot_generator_args)
else()
    set(_smrobot_generator_args -G "${SMROBOT_PACKAGE_EXAMPLES_GENERATOR}")
endif()

file(REMOVE_RECURSE "${SMROBOT_PACKAGE_EXAMPLES_CHECK_ROOT}")
file(MAKE_DIRECTORY "${SMROBOT_PACKAGE_EXAMPLES_CHECK_ROOT}")

set(_selection_source "${SMROBOT_PACKAGE_EXAMPLES_CHECK_ROOT}/selection_source")
set(_selection_binary "${SMROBOT_PACKAGE_EXAMPLES_CHECK_ROOT}/selection_binary")
file(MAKE_DIRECTORY "${_selection_source}")
file(WRITE "${_selection_source}/CMakeLists.txt" [=[
cmake_minimum_required(VERSION 3.20)
project(SMRobotPackageComponentSelectionCheck LANGUAGES CXX)

find_package(SMRobotPlatform CONFIG REQUIRED COMPONENTS AssetCore)
if(NOT TARGET SMRobotPlatform::AssetCore)
    message(FATAL_ERROR "SMRobotPlatform::AssetCore was not imported.")
endif()
if(TARGET SMRobotPlatform::SceneCore)
    message(FATAL_ERROR "SMRobotPlatform::SceneCore was imported without being requested.")
endif()
if(TARGET SMRobotPlatform::RenderCore)
    message(FATAL_ERROR "SMRobotPlatform::RenderCore was imported without being requested.")
endif()
if(TARGET SMRobotPlatform::CameraCore)
    message(FATAL_ERROR "SMRobotPlatform::CameraCore was imported without being requested.")
endif()
if(TARGET SMRobotPlatform::SensorCore)
    message(FATAL_ERROR "SMRobotPlatform::SensorCore was imported without being requested.")
endif()
if(TARGET SMRobotPlatform::SimulationProject)
    message(FATAL_ERROR "SMRobotPlatform::SimulationProject was imported without being requested.")
endif()
if(TARGET SMRobotPlatform::SimulationRuntime)
    message(FATAL_ERROR "SMRobotPlatform::SimulationRuntime was imported without being requested.")
endif()
if(TARGET SMRobotPlatform::SensorSimulation)
    message(FATAL_ERROR "SMRobotPlatform::SensorSimulation was imported without being requested.")
endif()
if(TARGET SMRobotPlatform::RobotRenderBridge)
    message(FATAL_ERROR "SMRobotPlatform::RobotRenderBridge was imported without being requested.")
endif()
if(TARGET SMRobotPlatform::VisualizationSDK)
    message(FATAL_ERROR "SMRobotPlatform::VisualizationSDK was imported without being requested.")
endif()
if(TARGET assimp::assimp OR TARGET assimp)
    message(FATAL_ERROR "Assimp was imported as an AssetCore public dependency.")
endif()
if(DEFINED AssetCore_PUBLIC_DEPENDENCIES AND
   "${AssetCore_PUBLIC_DEPENDENCIES}" MATCHES "assimp")
    message(FATAL_ERROR "AssetCore public dependency list exposes Assimp.")
endif()

find_package(SMRobotPlatform CONFIG REQUIRED COMPONENTS CameraCore SensorCore)
if(NOT TARGET SMRobotPlatform::CameraCore)
    message(FATAL_ERROR "SMRobotPlatform::CameraCore was not imported.")
endif()
if(NOT TARGET SMRobotPlatform::SensorCore)
    message(FATAL_ERROR "SMRobotPlatform::SensorCore was not imported.")
endif()
if(TARGET SMRobotPlatform::SceneCore)
    message(FATAL_ERROR "SMRobotPlatform::SceneCore was imported by CameraCore/SensorCore.")
endif()
if(TARGET SMRobotPlatform::RenderCore)
    message(FATAL_ERROR "SMRobotPlatform::RenderCore was imported by CameraCore/SensorCore.")
endif()
if(TARGET SMRobotPlatform::SimulationRuntime)
    message(FATAL_ERROR "SMRobotPlatform::SimulationRuntime was imported by CameraCore/SensorCore.")
endif()
if(TARGET SMRobotPlatform::SensorSimulation)
    message(FATAL_ERROR "SMRobotPlatform::SensorSimulation was imported by CameraCore/SensorCore.")
endif()
if(DEFINED CameraCore_PUBLIC_DEPENDENCIES AND
   "${CameraCore_PUBLIC_DEPENDENCIES}" MATCHES "CustomLog")
    message(FATAL_ERROR "CameraCore public dependency list exposes CustomLog.")
endif()
if(DEFINED SensorCore_PUBLIC_DEPENDENCIES AND
   NOT "${SensorCore_PUBLIC_DEPENDENCIES}" STREQUAL "Eigen3::Eigen")
    message(FATAL_ERROR "SensorCore public dependency list changed unexpectedly: ${SensorCore_PUBLIC_DEPENDENCIES}")
endif()

find_package(SMRobotPlatform CONFIG REQUIRED COMPONENTS ProjectSimulationSDK)
if(NOT TARGET SMRobotPlatform::ProjectSimulationSDK)
    message(FATAL_ERROR "SMRobotPlatform::ProjectSimulationSDK was not imported.")
endif()
if(TARGET SMRobotPlatform::SimulationProject)
    message(FATAL_ERROR "SMRobotPlatform::SimulationProject was imported without being requested.")
endif()

find_package(SMRobotPlatform CONFIG REQUIRED COMPONENTS SimulationProject)
if(NOT TARGET SMRobotPlatform::SimulationProject)
    message(FATAL_ERROR "SMRobotPlatform::SimulationProject was not imported.")
endif()
if(TARGET SMRobotPlatform::SimulationRuntime)
    message(FATAL_ERROR "SMRobotPlatform::SimulationRuntime was imported by SimulationProject.")
endif()
if(TARGET SMRobotPlatform::SensorSimulation)
    message(FATAL_ERROR "SMRobotPlatform::SensorSimulation was imported by SimulationProject.")
endif()
if(DEFINED SimulationProject_PUBLIC_DEPENDENCIES AND
   "${SimulationProject_PUBLIC_DEPENDENCIES}" MATCHES "RobotPlatformAuthorization")
    message(FATAL_ERROR "SimulationProject public dependency list exposes RobotPlatformAuthorization.")
endif()

find_package(SMRobotPlatform CONFIG REQUIRED COMPONENTS SimulationRuntime)
if(NOT TARGET SMRobotPlatform::SimulationRuntime)
    message(FATAL_ERROR "SMRobotPlatform::SimulationRuntime was not imported.")
endif()
if(NOT TARGET SMRobotPlatform::SimulationProject)
    message(FATAL_ERROR "SMRobotPlatform::SimulationRuntime did not import SimulationProject.")
endif()
if(NOT TARGET SMRobotPlatform::SensorCore)
    message(FATAL_ERROR "SMRobotPlatform::SimulationRuntime did not import SensorCore.")
endif()
if(TARGET SMRobotPlatform::SensorSimulation)
    message(FATAL_ERROR "SMRobotPlatform::SensorSimulation was imported by SimulationRuntime; this would recreate the runtime/sensor DLL cycle.")
endif()
if(DEFINED SimulationRuntime_PUBLIC_DEPENDENCIES AND
   "${SimulationRuntime_PUBLIC_DEPENDENCIES}" MATCHES "SensorSimulation")
    message(FATAL_ERROR "SimulationRuntime public dependency list exposes SensorSimulation.")
endif()

find_package(SMRobotPlatform CONFIG REQUIRED COMPONENTS SensorSimulation)
if(NOT TARGET SMRobotPlatform::SensorSimulation)
    message(FATAL_ERROR "SMRobotPlatform::SensorSimulation was not imported.")
endif()
if(NOT TARGET SMRobotPlatform::SimulationRuntime)
    message(FATAL_ERROR "SMRobotPlatform::SensorSimulation did not import SimulationRuntime.")
endif()

find_package(SMRobotPlatform CONFIG REQUIRED COMPONENTS VisualizationSDK)
if(NOT TARGET SMRobotPlatform::VisualizationSDK)
    message(FATAL_ERROR "SMRobotPlatform::VisualizationSDK was not imported.")
endif()
if(NOT TARGET SMRobotPlatform::SimulationRuntime)
    message(FATAL_ERROR "SMRobotPlatform::VisualizationSDK did not import SimulationRuntime.")
endif()
if(TARGET SMRobotPlatform::SceneCore)
    message(FATAL_ERROR "SMRobotPlatform::VisualizationSDK imported SceneCore as a public dependency.")
endif()
if(TARGET SMRobotPlatform::RenderCore)
    message(FATAL_ERROR "SMRobotPlatform::VisualizationSDK imported RenderCore as a public dependency.")
endif()
if(TARGET SMRobotPlatform::RobotRenderBridge)
    message(FATAL_ERROR "SMRobotPlatform::VisualizationSDK imported RobotRenderBridge as a public dependency.")
endif()
if(DEFINED VisualizationSDK_PUBLIC_DEPENDENCIES AND
   "${VisualizationSDK_PUBLIC_DEPENDENCIES}" MATCHES "RenderCore|SceneCore|RobotRenderBridge")
    message(FATAL_ERROR "VisualizationSDK public dependency list exposes render-chain implementation components.")
endif()

find_package(SMRobotPlatform CONFIG REQUIRED COMPONENTS RenderCore)
if(NOT TARGET SMRobotPlatform::RenderCore)
    message(FATAL_ERROR "SMRobotPlatform::RenderCore was not imported.")
endif()
if(NOT TARGET SMRobotPlatform::AssetCore)
    message(FATAL_ERROR "SMRobotPlatform::RenderCore did not import AssetCore.")
endif()
if(DEFINED RenderCore_PUBLIC_DEPENDENCIES AND
   "${RenderCore_PUBLIC_DEPENDENCIES}" MATCHES "assimp")
    message(FATAL_ERROR "RenderCore public dependency list exposes Assimp.")
endif()

find_package(SMRobotPlatform CONFIG REQUIRED COMPONENTS SceneCore)
if(NOT TARGET SMRobotPlatform::SceneCore)
    message(FATAL_ERROR "SMRobotPlatform::SceneCore was not imported.")
endif()
if(NOT TARGET SMRobotPlatform::RenderCore)
    message(FATAL_ERROR "SMRobotPlatform::SceneCore did not import RenderCore.")
endif()
if(NOT TARGET SMRobotPlatform::CameraCore)
    message(FATAL_ERROR "SMRobotPlatform::SceneCore did not import CameraCore.")
endif()
if(DEFINED SceneCore_PUBLIC_DEPENDENCIES AND
   "${SceneCore_PUBLIC_DEPENDENCIES}" MATCHES "CustomLog")
    message(FATAL_ERROR "SceneCore public dependency list exposes CustomLog.")
endif()

find_package(SMRobotPlatform CONFIG REQUIRED COMPONENTS RobotRenderBridge)
if(NOT TARGET SMRobotPlatform::RobotRenderBridge)
    message(FATAL_ERROR "SMRobotPlatform::RobotRenderBridge was not imported.")
endif()
if(NOT TARGET SMRobotPlatform::SceneCore)
    message(FATAL_ERROR "SMRobotPlatform::RobotRenderBridge did not import SceneCore.")
endif()
if(NOT TARGET SMRobotPlatform::RenderCore)
    message(FATAL_ERROR "SMRobotPlatform::RobotRenderBridge did not import RenderCore.")
endif()
if(NOT TARGET SMRobotPlatform::SimulationRuntime)
    message(FATAL_ERROR "SMRobotPlatform::RobotRenderBridge did not import SimulationRuntime.")
endif()
if(NOT TARGET SMRobotCore::RobotInstance)
    message(FATAL_ERROR "SMRobotPlatform::RobotRenderBridge did not import RobotInstance.")
endif()

find_package(SMRobotCore CONFIG REQUIRED COMPONENTS RobotCore Kinematics RobotTrajectoryCore RobotIO)
if(NOT TARGET SMRobotCore::RobotIO)
    message(FATAL_ERROR "SMRobotCore::RobotIO was not imported.")
endif()
if(NOT TARGET SMRobotCore::RobotCore)
    message(FATAL_ERROR "SMRobotCore::RobotCore was not imported.")
endif()
if(NOT TARGET SMRobotCore::Kinematics)
    message(FATAL_ERROR "SMRobotCore::Kinematics was not imported.")
endif()
if(NOT TARGET SMRobotCore::RobotTrajectoryCore)
    message(FATAL_ERROR "SMRobotCore::RobotTrajectoryCore was not imported.")
endif()
find_package(SMRobotCore CONFIG REQUIRED COMPONENTS RobotRuntime RobotInstance Collision)
if(NOT TARGET SMRobotCore::RobotRuntime)
    message(FATAL_ERROR "SMRobotCore::RobotRuntime was not imported.")
endif()
if(NOT TARGET SMRobotCore::RobotInstance)
    message(FATAL_ERROR "SMRobotCore::RobotInstance was not imported.")
endif()
if(NOT TARGET SMRobotCore::Collision)
    message(FATAL_ERROR "SMRobotCore::Collision was not imported.")
endif()
]=])

execute_process(
    COMMAND "${CMAKE_COMMAND}"
        -S "${_selection_source}"
        -B "${_selection_binary}"
        ${_smrobot_generator_args}
        "-DCMAKE_PREFIX_PATH=${SMROBOT_PACKAGE_EXAMPLES_SDK_PREFIX}"
    RESULT_VARIABLE _selection_result
    OUTPUT_VARIABLE _selection_output
    ERROR_VARIABLE _selection_error
)
if(NOT _selection_result EQUAL 0)
    message(STATUS "${_selection_output}")
    message(STATUS "${_selection_error}")
    message(FATAL_ERROR "Package component selection check failed.")
endif()

set(_missing_source "${SMROBOT_PACKAGE_EXAMPLES_CHECK_ROOT}/missing_source")
set(_missing_binary "${SMROBOT_PACKAGE_EXAMPLES_CHECK_ROOT}/missing_binary")
file(MAKE_DIRECTORY "${_missing_source}")
file(WRITE "${_missing_source}/CMakeLists.txt" [=[
cmake_minimum_required(VERSION 3.20)
project(SMRobotPackageMissingComponentCheck LANGUAGES CXX)
find_package(SMRobotCore CONFIG REQUIRED COMPONENTS DefinitelyMissingComponent)
]=])

execute_process(
    COMMAND "${CMAKE_COMMAND}"
        -S "${_missing_source}"
        -B "${_missing_binary}"
        ${_smrobot_generator_args}
        "-DCMAKE_PREFIX_PATH=${SMROBOT_PACKAGE_EXAMPLES_SDK_PREFIX}"
    RESULT_VARIABLE _missing_result
    OUTPUT_VARIABLE _missing_output
    ERROR_VARIABLE _missing_error
)
if(_missing_result EQUAL 0)
    message(FATAL_ERROR "Missing component check unexpectedly configured successfully.")
endif()

set(_missing_combined_output "${_missing_output}\n${_missing_error}")
if(NOT _missing_combined_output MATCHES "Unsupported component: DefinitelyMissingComponent")
    message(STATUS "${_missing_combined_output}")
    message(FATAL_ERROR "Missing component check failed for an unexpected reason.")
endif()

message(STATUS "SMRobot package component selection checks passed.")
